# Generated by Django 5.0 on 2023-12-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
