# Generated by Django 5.0 on 2023-12-29 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_courseschedule_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
